# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gleam_platform.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('signup_begin_time', models.DateTimeField()),
                ('signup_end_time', models.DateTimeField()),
                ('submit_begin_time', models.DateTimeField()),
                ('submit_end_time', models.DateTimeField()),
                ('announcement_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('evaluation', models.TextField()),
                ('prizes', models.TextField()),
                ('data_description', models.TextField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_id', models.CharField(max_length=18)),
                ('nick_name', models.CharField(max_length=24)),
                ('school', models.CharField(max_length=80)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'others')], default='O', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Contestant')),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_organization', models.CharField(max_length=80, verbose_name='组织')),
            ],
            options={
                'verbose_name': 'Organizer',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('O', 'Organizer'), ('C', 'Contestant')], max_length=2)),
                ('Contestant_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Contestant')),
                ('organizer_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Organizer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data', models.FileField(upload_to=gleam_platform.models.generate_filename)),
                ('time', models.DateTimeField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('members', models.ManyToManyField(through='gleam_platform.Membership', to='gleam_platform.Contestant')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Team'),
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Team'),
        ),
        migrations.AddField(
            model_name='contest',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Organizer'),
        ),
    ]
