# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gleam_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('time', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='unique_id',
            field=models.CharField(default='X', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_team_member_num',
            field=models.IntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.AddField(
            model_name='record',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Team'),
        ),
    ]
