# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gleam_platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='evaluation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=80, unique=True, verbose_name='email address'),
        ),
    ]
