# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gleam_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_team', to='gleam_platform.Contestant'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='team_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='team_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contest',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Tournament'),
        ),
        migrations.AlterField(
            model_name='record',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Contest'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_member',
            field=models.IntegerField(null=True),
        ),
    ]
