# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gleam_platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboarditem',
            name='submit_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='resident_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboarditem',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Team'),
        ),
    ]
