# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gleam_platform', '0002_auto_20171207_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Image'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='nick_name',
            field=models.CharField(blank=True, default='Alice', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='resident_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='school',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='contestant_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Contestant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organizer_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Organizer'),
        ),
    ]
