# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gleam_platform', '0003_auto_20171210_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='last_promote_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='donation',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizer',
            name='profile_page_visit_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='last_csv_upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='team_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboarditem',
            name='submit_num',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_team_member_num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='contestant_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Contestant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organizer_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Organizer'),
        ),
    ]
