# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gleam_platform', '0004_auto_20171212_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gleam_platform.Image'),
        ),
    ]
